version: '3.6'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - default
      - inbox
  database:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - default
      - inbox
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-inbox}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-inbox}
      - POSTGRES_DB=${POSTGRES_DB:-inbox}
  inbox:
    image: ${DOCKER_IMAGE_NAME:-ilha/inbox}:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    networks:
      - default
      - inbox
    environment:
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://inbox:inbox@database:5432/inbox}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_DATABASE=${REDIS_DATABASE:-15}
      - TIME_ZONE=${TIME_ZONE:-UTC}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-webmaster@localhost}
      - SERVER_EMAIL=${SERVER_EMAIL:-root@localhost}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-false}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-false}
      - ADMINS=${ADMINS:-Ilhasoft|contato@ilhasoft.com.br}
      - SEND_EMAILS=${SEND_EMAILS:-true}
      - COMPRESS_ENABLED=${DEBUG:-false}
      - COMPRESS_OFFLINE=${DEBUG:-false}
      - RAVEN_CONFIG=${RAVEN_CONFIG}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_ACCESS_KEY}
    depends_on:
      - database
      - redis

networks:
  inbox:
    external: true
