# Generated by Django 2.0.8 on 2018-12-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0026_fix_org_config_rapidpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL')),
                ('short', models.CharField(max_length=50, verbose_name='Short URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_urls', to='orgs.Org', verbose_name='Organization')),
            ],
        ),
    ]
