# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def populate_inserted_on(apps, schema_editor):
    Message = apps.get_model('msgs', 'Message')

    msgs = Message.objects.all()

    for msg in msgs:
        msg.inserted_on = msg.created_on
        msg.save(update_fields=('inserted_on',))

    print("Updated %d messages" % len(msgs))


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0057_auto_20170718_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inserted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)
        ),
        migrations.RunPython(populate_inserted_on)
    ]
