# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0058_message_inserted_on'),
        ('msgs', '0059_new_modified_msgs_index'),
    ]

    operations = [
    ]
