# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0060_merge_20171221_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='modified_on',
            field=models.DateTimeField(help_text='When message was last modified', null=True),
        ),
    ]
