# Generated by Django 2.0.8 on 2018-09-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0061_auto_20180720_1337'),
        ('msgs', '0060_auto_20180814_2109'),
    ]

    operations = [
    ]
