# Generated by Django 2.1.5 on 2019-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0062_merge_20180919_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='When message was last modified', null=True),
        ),
    ]
